sudo: false
dist: trusty

language: php
php: 
  - 7.1
  - 7.2
  - nightly

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/node_modules

before_script:
  - composer validate
  - composer install --prefer-dist --no-suggest
  - composer outdated --direct
  - composer require --dev jakub-onderka/php-parallel-lint

script:
  - chmod +x ./artisan
  - vendor/bin/parallel-lint --blame --exclude vendor/ .
  - composer require --dev melihovv/laravel-compile-views
  - ./artisan view:compile
  - vendor/bin/parallel-lint storage/framework/views/
  - yarn
  - yarn run dev
  - cp -v .env.example .env
  - sed -e 's|^BASIC_AUTH_USERNAME=|&user|' -e 's|^BASIC_AUTH_PASSWORD=|&secret|' -i .env
  - sed -e 's|^APP_URL=|APP_URL=http://localhost:8080|' -i .env
  - ./artisan key:generate
  - echo ".databases" | sqlite3 database/database.sqlite
  - ./artisan serve --host=localhost --port=8080 &
  - vendor/bin/phpunit --configuration ./phpunit.xml
  - wget -qSO- "http://localhost:8080/" | grep -F -x '</html>'
